### PR TITLE
Update max print speed from 6 to 14

### LINKED ISSUE #69: Why is the maximum print speed 6?
According to this document: https://support.zebra.com/cpws/docs/zpl/PR_Command.pdf, it seems like the max should be 14. I would be happy to create a pull request unless there is some reason for the restriction to `6`.

### PR DESCRIPTION
**Pull request by eke-bb**
Closes #69 

https://support.zebra.com/cpws/docs/zpl/PR_Command.pdf

### CODE REVIEW

**Review by bbulpett — APPROVED** [review]
LGTM 😎

**Comment by eke-bb** [comment]
@bbulpett any idea on a timeline when this might be available to pull down from rubygems? i'm working on a feature that relies on this change and would like to give an update to stakeholders on a when it might be ready.

**Review by LagTag — APPROVED** [review]

**Review by mtking2 — APPROVED** [review]

**Comment by mtking2** [comment]
I can push it out over the weekend if need be.

**Comment by eke-bb** [comment]
@mtking2 that would be great, thank you!

**Comment by eke-bb** [comment]
@mtking2 Good morning! Just checking in regarding when you think this might be able to be merged?

**Comment by mtking2** [comment]
Morning @eke-bb! Sorry for the delay. I'll go ahead and merge this and push it out to ruby gems later today.

**Comment by mtking2** [comment]
@eke-bb 🚀 #73

**Pull request merged**
